name: food_swipe_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.2+5

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  geolocator: ^14.0.1
  http: ^1.4.0
  flutter_card_swiper: ^7.0.2
  flutter_dotenv: ^5.2.1
  url_launcher: ^6.2.6
  flutter_launcher_icons: ^0.14.3
  shared_preferences: ^2.5.3
  story_view: ^0.16.5
  cached_network_image: ^3.3.1
  carousel_slider: ^5.1.1
  intl: ^0.20.2
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  path: ^1.8.3
  collection: ^1.18.0
  # Firebase 相關依賴項
  firebase_core: ^3.6.0
  firebase_storage: ^12.2.2
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.5
  image_picker: ^1.0.7
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/loading_pig.png
    - assets/restaurants/
    - assets/restaurants_collection/
    - assets/restaurants_collection/ahan/
    - assets/restaurants_collection/aming/
    - assets/restaurants_collection/asong/
    - assets/restaurants_collection/atang/
    - assets/restaurants_collection/chikan/
    - assets/restaurants_collection/chous/
    - assets/restaurants_collection/douhsiao/
    - assets/restaurants_collection/fusheng/
    - assets/restaurants_collection/tongji/
    - assets/restaurants_collection/yifeng/
    - assets/restaurants_collection/shengli/
    - assets/restaurants_collection/achuan/
    - assets/restaurants_collection/huaijiu/
    - assets/restaurants_collection/izuminami/
    - assets/restaurants_collection/caijia/
    - assets/restaurants_collection/shijingjiu/
    - assets/restaurants_collection/jinde/
    - assets/restaurants_collection/weijia/
    - assets/restaurants_collection/lanji/
    - assets/restaurants_collection/xiezhanggui/
    - assets/restaurants_collection/shanghaochi/
    - assets/restaurants_collection/yejia/
    - assets/restaurants_collection/yongle/
    - assets/restaurants_collection/ajuan/
    - assets/restaurants_collection/acun/
    - assets/restaurants_collection/chengjiang/
    - assets/restaurants_collection/xiluodian/
    - assets/restaurants_collection/wenzhang/
    - assets/restaurants_collection/niujiazhuang/
    - assets/tainan_markets.json
    - .env

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "icon.png"
