name: food_swipe_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+2

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  geolocator: ^14.0.1
  http: ^1.4.0
  flutter_card_swiper: ^7.0.2
  flutter_dotenv: ^5.2.1
  url_launcher: ^6.2.6
  flutter_launcher_icons: ^0.14.3
  shared_preferences: ^2.5.3
  story_view: ^0.16.5
  cached_network_image: ^3.3.1
  carousel_slider: ^5.1.1
  intl: ^0.20.2
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/loading_pig.png
    - assets/restaurants/
    - assets/restaurants_collection/
    - .env
    - lib/data/tainan_restaurants.json

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "icon.png"
